CREATE TABLE IF NOT EXISTS DEPARTMENT(
 EMPLOYE_ID TEXT,
 NAME TEXT,
 DEPARTMENT_ID TEXT,
 MANAGER_ID TEXT,
 SALARY REAL

);
INSERT INTO DEPARTMENT(EMPLOYE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY ) VALUES
  ("100", "STEVEN KING ", "90", "100", 24000),
  ("101", "NEENA KOCCHAR", "90", "100", 17000),
  ("102", "LEX DEHAAN", "90", "102", 9000),
  ("103", "BRUCE LEE", "60", "103", 4800),
  ("104", "DIANA WILLS", "60", "103", 6000);

SELECT DEPARTMENT_ID AS "department code", 
COUNT(*) AS "No of employes"
FROM DEPARTMENT
 GROUP BY DEPARTMENT_ID;


SELECT department_id AS "department code",
SUM(salary) AS "total salary"
FROM DEPARTMENT
WHERE MANAGER_ID = "103"
GROUP BY department_id;